tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'git'
brew 'ruby-install'
brew 'chruby'
cask 'iterm2'
cask 'slack'
cask 'google-chrome'
cask 'macdown'
cask 'spectacle'

