#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brewfile -c "${CONFIG}" "${@}"

ruby-install ruby-2.4.4 --no-reinstall
ruby-install ruby-2.7.1 --no-reinstall
ruby-install ruby-2.6.5 --no-reinstall
ruby-install ruby-2.6.3 --no-reinstall

brew link --overwrite node

heroku plugins:install heroku-accounts

npm install -g n
npm install -g bower
npm install -g avn avn-nvm avn-n
avn setup

curl http://localhost:15672/cli/rabbitmqadmin -o /usr/local/bin/rabbitmqadmin && chmod +x /usr/local/bin/rabbitmqadmin
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

sudo puma-dev -setup
puma-dev -install
